/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface HistogramComponent {
    }
    interface MyComponent {
        "data": string;
        "height": number;
        "width": number;
    }
}
declare global {
    interface HTMLHistogramComponentElement extends Components.HistogramComponent, HTMLStencilElement {
    }
    var HTMLHistogramComponentElement: {
        prototype: HTMLHistogramComponentElement;
        new (): HTMLHistogramComponentElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "histogram-component": HTMLHistogramComponentElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface HistogramComponent {
    }
    interface MyComponent {
        "data"?: string;
        "height"?: number;
        "width"?: number;
    }
    interface IntrinsicElements {
        "histogram-component": HistogramComponent;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "histogram-component": LocalJSX.HistogramComponent & JSXBase.HTMLAttributes<HTMLHistogramComponentElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
