/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppolloButton {
        "appearance": string;
        "text": string;
    }
    interface AppolloModal {
        "appearance": string;
        "buttons": string;
        "closeIcon": string;
        "header": string;
        "isopen": boolean;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLAppolloButtonElement extends Components.AppolloButton, HTMLStencilElement {
    }
    var HTMLAppolloButtonElement: {
        prototype: HTMLAppolloButtonElement;
        new (): HTMLAppolloButtonElement;
    };
    interface HTMLAppolloModalElement extends Components.AppolloModal, HTMLStencilElement {
    }
    var HTMLAppolloModalElement: {
        prototype: HTMLAppolloModalElement;
        new (): HTMLAppolloModalElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "appollo-button": HTMLAppolloButtonElement;
        "appollo-modal": HTMLAppolloModalElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface AppolloButton {
        "appearance"?: string;
        "text"?: string;
    }
    interface AppolloModal {
        "appearance"?: string;
        "buttons"?: string;
        "closeIcon"?: string;
        "header"?: string;
        "isopen"?: boolean;
        "onAction"?: (event: CustomEvent<any>) => void;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "appollo-button": AppolloButton;
        "appollo-modal": AppolloModal;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "appollo-button": LocalJSX.AppolloButton & JSXBase.HTMLAttributes<HTMLAppolloButtonElement>;
            "appollo-modal": LocalJSX.AppolloModal & JSXBase.HTMLAttributes<HTMLAppolloModalElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
