/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface WebComponent {
        "src": string;
    }
}
declare global {
    interface HTMLWebComponentElement extends Components.WebComponent, HTMLStencilElement {
    }
    var HTMLWebComponentElement: {
        prototype: HTMLWebComponentElement;
        new (): HTMLWebComponentElement;
    };
    interface HTMLElementTagNameMap {
        "web-component": HTMLWebComponentElement;
    }
}
declare namespace LocalJSX {
    interface WebComponent {
        "src"?: string;
    }
    interface IntrinsicElements {
        "web-component": WebComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "web-component": LocalJSX.WebComponent & JSXBase.HTMLAttributes<HTMLWebComponentElement>;
        }
    }
}
